version: '3.9'
services:
  api:
    build: .                # ← читает Dockerfile в корне
    environment:
      DB_DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      REDIS_ADDR: redis:6379
    depends_on: [postgres, redis]
    ports:
      - "8080:8080"         # localhost:8080 → контейнер:8080

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data