version: "3.9"

services:
  backend:
    build: .
    env_file: .env
    environment:
      DB_DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      REDIS_ADDR: redis:6379
    depends_on:
      - postgres
      - redis
    ports: ["8080:8080"]

  postgres:
    image: postgres:15
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: ["${POSTGRES_PORT}:5432"]

  redis:
    image: redis:7
    env_file: .env
    ports: ["${REDIS_PORT}:6379"]
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: